/* eslint-disable */
require('./apple')
require('./mine1')
require('./mine10')
require('./mine11')
require('./mine12')
require('./mine2')
require('./mine3')
require('./mine5')
require('./mine6')
require('./mine7')
require('./mine8')
require('./mine9')
require('./robot')
